---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-data-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 800Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/mysql"
...
