FROM nginx:1.27.0

# Declare variables
ARG UID="nginx"
ARG GID="nginx"
ARG CONFIG="wordpress.conf"

# Install the GNU Compiler Collection
RUN apt-get update && apt-get install -y \
        gcc mono-mcs \
    && rm -rf /var/lib/apt/lists/* \
    && rm /etc/nginx/conf.d/default.conf \
    # Create the necessary directories
    && mkdir -p /var/cache/nginx/client_temp \
        /var/cache/nginx/proxy_temp \
        /var/cache/nginx/fastcgi_temp \
        /var/cache/nginx/scgi_temp \
        /var/cache/nginx/uwsgi_temp \
        /etc/nginx/sites-available \
        /etc/nginx/sites-enabled \
        /etc/nginx/blocklists

# Copy the NGINX configuration files
COPY ${CONFIG} /etc/nginx/sites-available
COPY nginx.pid /var/log/nginx
COPY nginx.conf /etc/nginx

# Create the symbolic link
RUN ln -s /etc/nginx/sites-available/${CONFIG} /etc/nginx/sites-enabled/${CONFIG} \
    # Claim ownership for a non-root user
    && chown -R ${UID}:${GID} /usr/share/nginx /var/log/nginx /etc/nginx

# Set the working directory
WORKDIR /data/www

# Switch to the NGINX user
USER www-data