---
- name: Build Docker images
  hosts: darwin
  connection: local
  vars_files: defaults/main.yaml
  gather_facts: false
  tasks:
    - name: Run the MariaDB Dockerfile
      ansible.builtin.command: docker build -f Dockerfile-MariaDB -t mariadb .
    - name: Tag the MariaDB build
      ansible.builtin.command: docker image tag mariadb:latest {{ MARIADB }}
    - name: Push the MariaDB build to DockerHub
      ansible.builtin.command: docker push {{ MARIADB }}
    - name: Run the WordPress Dockerfile
      ansible.builtin.command: docker build -f Dockerfile-WordPress -t wordpress .
    - name: Tag the WordPress build
      ansible.builtin.command: docker image tag wordpress:latest {{ WORDPRESS }}
    - name: Push the WordPress build to DockerHub
      ansible.builtin.command: docker push {{ WORDPRESS }}
    - name: Run the NGiNX Dockerfile
      ansible.builtin.command: docker build -f Dockerfile-NGiNX -t nginx .
    - name: Tag the NGiNX build
      ansible.builtin.command: docker image tag nginx:latest {{ NGINX }}
    - name: Push the NGiNX build to DockerHub
      ansible.builtin.command: docker push {{ NGINX }}
...