---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: wordpress
  namespace: default
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      volumes:
        - name: wp-data-storage
          persistentVolumeClaim:
            claimName: wp-data-claim
      containers:
        - name: wordpress
          image: docker.io/nausicaan/wordpress:8.2-fpm
          resources:
            requests:
              cpu: "100m"
              memory: "150Mi"
            limits:
              cpu: "300m"
              memory: "300Mi"
          volumeMounts:
            - mountPath: /data/www
              name: wp-data-storage
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
...
